// 참조 디자인 토큰을 Docker 프론트 앱에 매핑하는 Tailwind 설정
import type { Config } from "tailwindcss";

export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    colors: {
      transparent: "transparent",
      current: "currentColor",
      black: "#000000",
      white: "#ffffff",
      primary: "#000000",
      "on-primary": "#ffffff",
      "ink-deep": "#090909",
      charcoal: "#525252",
      body: "#737373",
      mute: "#a3a3a3",
      background: "#f9f9f9",
      surface: "#f9f9f9",
      canvas: "#ffffff",
      "surface-canvas": "#ffffff",
      "surface-soft": "#fafafa",
      "surface-card": "#ffffff",
      "surface-dark": "#171717",
      "surface-container-lowest": "#ffffff",
      "surface-container-low": "#f3f3f3",
      "surface-container": "#eeeeee",
      "surface-container-high": "#e8e8e8",
      "surface-container-highest": "#e2e2e2",
      "surface-dim": "#dadada",
      secondary: "#5e5e5e",
      "on-surface": "#1b1b1b",
      "on-surface-variant": "#4c4546",
      hairline: "#e5e5e5",
      "border-hairline": "#e5e5e5",
      "hairline-strong": "#d4d4d4",
      "border-strong": "#000000",
      "focus-ring": "rgba(59,130,246,0.5)",
      "data-flow": "#a3a3a3",
      "data-label": "#525252",
      "inverse-surface": "#303030",
      "status-pending": "#737373",
      "status-running": "#000000",
      "status-done": "#27c93f",
      "status-failed": "#ff5f56",
      "status-skipped": "#a3a3a3",
      "term-red": "#ff5f56",
      "term-yellow": "#f59e0b",
      "term-green": "#27c93f",
      error: "#ba1a1a",
      "error-container": "#ffdad6",
      "on-error-container": "#93000a",
    },
    fontFamily: {
      display: ["Plus Jakarta Sans", "Pretendard Variable", "Pretendard", "system-ui", "sans-serif"],
      sans: ["Inter", "Pretendard Variable", "Pretendard", "ui-sans-serif", "system-ui", "sans-serif"],
      mono: ["JetBrains Mono", "ui-monospace", "SFMono-Regular", "Menlo", "monospace"],
    },
    borderRadius: {
      none: "0",
      sm: "0.5rem",
      DEFAULT: "1rem",
      md: "1.5rem",
      lg: "2rem",
      xl: "3rem",
      "2xl": "2rem",
      "3xl": "3rem",
      full: "9999px",
    },
    fontSize: {
      "display-xl": ["36px", { lineHeight: "1.11", fontWeight: "600" }],
      "display-lg": ["30px", { lineHeight: "1.2", fontWeight: "600" }],
      "heading-lg": ["24px", { lineHeight: "1.33", fontWeight: "700" }],
      "heading-md": ["20px", { lineHeight: "1.4", fontWeight: "600" }],
      "heading-sm": ["18px", { lineHeight: "1.33", fontWeight: "600" }],
      "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
      "body-strong": ["16px", { lineHeight: "1.5", fontWeight: "600" }],
      "body-sm": ["14px", { lineHeight: "1.43", fontWeight: "400" }],
      "body-sm-strong": ["14px", { lineHeight: "1.43", fontWeight: "600" }],
      "caption-sm": ["12px", { lineHeight: "1.33", fontWeight: "400" }],
      "caption-strong": ["12px", { lineHeight: "1.33", fontWeight: "600" }],
      "data-label": ["11px", { lineHeight: "1.45", fontWeight: "500", letterSpacing: "0.02em" }],
      "code-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
      "code-sm": ["12px", { lineHeight: "1.5", fontWeight: "400" }],
      "button-md": ["14px", { lineHeight: "1", fontWeight: "600" }],
    },
    spacing: {
      0: "0",
      px: "1px",
      xxs: "2px",
      xs: "4px",
      sm: "8px",
      md: "12px",
      lg: "16px",
      xl: "24px",
      xxl: "32px",
      section: "88px",
      gutter: "1rem",
      "card-padding": "1.25rem",
      "section-gap": "2rem",
      "nav-height": "56px",
      "rail-width": "56px",
      1: "4px",
      2: "8px",
      3: "12px",
      4: "16px",
      5: "20px",
      6: "24px",
      7: "28px",
      8: "32px",
      9: "36px",
      10: "40px",
      11: "44px",
      12: "48px",
      14: "56px",
      16: "64px",
      18: "72px",
      20: "80px",
      24: "96px",
      28: "112px",
      32: "128px",
      36: "144px",
      40: "160px",
      48: "192px",
      56: "224px",
      64: "256px",
      72: "288px",
      80: "20rem",
      96: "24rem",
      120: "30rem",
    },
    extend: {
      borderWidth: { hairline: "1px" },
      boxShadow: {
        "running-ring": "0 0 0 6px rgba(0,0,0,0.04)",
      },
      backgroundImage: {
        "dot-grid": "radial-gradient(#e5e5e5 1px, transparent 1px)",
      },
    },
  },
  plugins: [],
} satisfies Config;
